openapi: 3.0.0
info:
  description: Definition of the operations available for the ASquare Dashboard
  title: ASquare APIs
  version: 0.0.1
servers:
  - url: http://localhost:3000/api
paths:
  /auth/login:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Bad request. Some of the inputs provided to the request aren't valid"
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: User password have expired
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Internal server error. Additional details will be contained on the server logs."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginCredentials"
        description: The request body for logging in.
        required: true
      operationId: userAuthentication
      summary: Logs in the user using user id and password
      tags:
        - Authentication
  /retail/customer:
    get:
      parameters:
        - description: The store identifier.
          in: header
          name: siteId
          required: true
          schema:
            enum:
              - UK
              - ROI
              - Pharmacy
            type: string
        - in: header
          name: channel
          required: true
          schema:
            enum:
              - Ecommerce
              - MOTO
              - APM
              - PDC
              - DPI
              - Clinics DPS
              - Mobile
              - Instore
            type: string
        - description: The customer's id.
          in: header
          name: customerId
          required: true
          schema:
            type: string
      responses:
        "200":
          description: none
          content:
            application/json:
              schema:
                title: string
  /user/login:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: >-
            Bad request. Some of the inputs provided to the request aren't
            valid.
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Not authenticated. The user session isn't valid.
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: The user isn't authorized to perform the specified request.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: >-
            Internal server error. Additional details will be contained on the
            server logs.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginCredentials"
        description: The request body for applying promotion codes to the shopping cart.
        required: true
      operationId: userAuthentication2
      summary: Logs in the user using user id and password
      tags:
        - Authentication
  /user/register:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: >-
            Bad request. Some of the inputs provided to the request aren't
            valid.
        "401":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Not authenticated. The user session isn't valid.
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: The user isn't authorized to perform the specified request.
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: >-
            Internal server error. Additional details will be contained on the
            server logs.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterResponse"
      operationId: userLogout
      summary: Logs out the user
      tags:
        - Authentication
components:
  schemas:
    LoginCredentials:
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    LoginResponse:
      type: object
      properties:
        userId:
          type: string
        personalDetails:
          $ref: "#/components/schemas/PersonalDetails"
    RegisterResponse:
      type: object
      properties:
        success:
          type: boolean
    PersonalDetails:
      type: object
      properties:
        profilePicture:
          type: string
        contactDetails:
          $ref: "#/components/schemas/ContactDetails"
        dateOfBirth:
          $ref: "#/components/schemas/DateOfBirth"
        accountStatus:
          type: string
          enum:
            - active
            - locked
            - disabled
            - inactive
            - pending
    ErrorResponse:
      properties:
        detail:
          description: Optional text that describes the error in more detail
          type: string
        instance:
          description: Optional UID to correlate message to logs
          type: string
        status:
          description: repeat of returned HTTP Status Code
          type: number
        title:
          description: >-
            Human readable summary message that may be displayed back to the
            user.
          maxLength: 1024
          minLength: 1
          type: string
        type:
          description: URI for type of error
          minLength: 1
          type: string
      required:
        - status
        - type
        - title
      type: object
    Contact:
      properties:
        email:
          $ref: "#/components/schemas/Email"
        phones:
          items:
            $ref: "#/components/schemas/Phone"
          type: array
      type: object
    ContactDetails:
      properties:
        contact:
          $ref: "#/components/schemas/Contact"
        name:
          $ref: "#/components/schemas/Name"
      type: object
    Email:
      properties:
        email:
          maxLength: 90
          minLength: 1
          type: string
        isValid:
          type: boolean
        type:
          type: string
      required:
        - email
        - isValid
      type: object
    Name:
      properties:
        birthLast:
          maxLength: 60
          minLength: 1
          type: string
        chosenFirst:
          maxLength: 30
          minLength: 1
          type: string
        first:
          maxLength: 30
          minLength: 1
          type: string
        last:
          maxLength: 60
          minLength: 1
          type: string
        middle:
          maxLength: 30
          minLength: 1
          type: string
      required:
        - first
        - last
      type: object
    Phone:
      properties:
        isValid:
          type: boolean
        phone:
          maxLength: 30
          minLength: 1
          type: string
        type:
          enum:
            - Home
            - Mobile
            - Work
          type: string
      required:
        - phone
        - isValid
      type: object
    DateOfBirth:
      type: object
      properties:
        day:
          type: string
          pattern: ^[0-9]{2}$
        month:
          type: string
        year:
          type: string
          pattern: ^[0-9]{4}$
tags:
  - description: Services to fulfill actions for ASquare Commerce Website
    name: ASquare Service
