openapi: 3.0.0
info:
  description: Definition of the operations available for the ASquare Dashboard
  title: ASquare APIs
  version: 0.0.1
servers:
  - url: http://localhost:3000/api
paths:
  /auth/login:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Bad request. Some of the inputs provided to the request aren't valid"
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: User password have expired
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Internal server error. Additional details will be contained on the server logs."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginBody"
        description: The request body for logging in.
        required: true
      operationId: userAuthentication
      summary: Logs in the user using email and password
      tags:
        - Authentication
  /auth/register:
    post:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
          description: Success
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Bad request. Some of the inputs provided to the request aren't valid"
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Internal server error. Additional details will be contained on the server logs."
      "requestBody":
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterBody"
        description: The request body for registering a user
        required: true
      operationId: userRegister
      summary: Register new user
      tags:
        - Authentication
  /auth/active/{confirmationCode}:
    get:
      parameters:
        - description: Confirmation code send by email
          in: path
          name: confirmationCode
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The requested completed successfully.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Bad request. Some of the inputs provided to the request aren't valid"
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Internal server error. Additional details will be contained on the server logs."
      operationId: userActivation
      summary: Activate user via email
      tags:
        - Authentication
  /auth/logout:
    get:
      parameters:
        - description: Confirm user is logged in
          in: cookie
          name: access_token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The requested completed successfully.
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Bad request. Some of the inputs provided to the request aren't valid"
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: User password have expired
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Internal server error. Additional details will be contained on the server logs."
      operationId: userLogout
      summary: Logout user
      tags:
        - Authentication
  /auth/resendemail:
    post:
      responses:
        "200":
          description: The request completed successfully
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Bad request. Some of the inputs provided to the request aren't valid"
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Internal server error. Additional details will be contained on the server logs."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ResendEmailBody"
      operationId: userResendEmail
      summary: Resend email for activating account
      tags:
        - Authentication
  /auth/protected:
    get:
      parameters:
        - description: Confirm user is logged in
          in: cookie
          name: access_token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The requested completed successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProtectedResponse"
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Bad request. Some of the inputs provided to the request aren't valid"
        "403":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: User password have expired
        "500":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: "Internal server error. Additional details will be contained on the server logs."
      operationId: userProtected
      summary: Protected Route
      tags:
        - Testing

components:
  schemas:
    LoginBody:
      properties:
        email:
          type: string
          pattern: ^[\w-\.]+@([\w-]+\.)+[\w-]{2,6}$
        password:
          type: string
      required:
        - email
        - password
    LoginResponse:
      type: object
      properties:
        userProfile:
          $ref: "#/components/schemas/UserProfile"
    RegisterBody:
      properties:
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
        alias:
          type: string
        email:
          type: string
          pattern: ^[\w-\.]+@([\w-]+\.)+[\w-]{2,6}$
        phones:
          type: string
          pattern: ^[0-9-+\s]{8,30}
        avatar:
          type: string
      required:
        - firstName
        - lastName
        - email
    RegisterResponse:
      properties:
        title:
          type: string
        detail:
          type: string
        userData:
          type: object
          properties:
            activationToken:
              type: string
            email:
              type: string
              pattern: ^[\w-\.]+@([\w-]+\.)+[\w-]{2,6}$
            name:
              type: string
    ResendEmailBody:
      properties:
        name:
          type: string
        email:
          type: string
          pattern: ^[\w-\.]+@([\w-]+\.)+[\w-]{2,6}$
        activationToken:
          type: string
    ProtectedResponse:
      properties:
        success:
          type: boolean
        user:
          $ref: "#/components/schemas/UserProfile"

    UserProfile:
      properties:
        firstName:
          type: string
        lastName:
          type: string
        middleName:
          type: string
          nullable: true
        alias:
          type: string
          nullable: true
        dateOfBirth:
          $ref: "#/components/schemas/DateOfBirth"
        email:
          type: string
          pattern: ^[\w-\.]+@([\w-]+\.)+[\w-]{2,6}$
        phones:
          type: array
          example: []
          nullable: true
          items:
            type: object
            properties:
              test:
                type: string
        #           type: string
        #           pattern: ^[0-9-+\s]{8,30}
        #           nullable: true
        role:
          type: string
          enum:
            - user
            - support
            - admin
          default: user
        avatar:
          type: string
          nullable: true
        favourites:
          type: array
          example: []
          nullable: true
          items:
            type: object
            properties:
              test:
                type: string
        productCreated:
          type: array
          example: []
          nullable: true
          items:
            type: object
            properties:
              test:
                type: string
        savedAddress:
          type: array
          example: []
          nullable: true
          items:
            type: object
            properties:
              test:
                type: string
        creditCards:
          type: array
          example: []
          nullable: true
          items:
            type: object
            properties:
              test:
                type: string
        isActive:
          type: string
          enum:
            - pending
            - active
            - blocked
          default: pending
        resetPasswordToken:
          type: string
        activationToken:
          nullable: true
          type: string
        resetPasswordExpires:
          type: string
          format: date-time

    ErrorResponse:
      properties:
        detail:
          description: Optional text that describes the error in more detail
          type: string
        instance:
          description: Optional UID to correlate message to logs
          type: string
        status:
          description: repeat of returned HTTP Status Code
          type: number
        title:
          description: >-
            Human readable summary message that may be displayed back to the
            user.
          maxLength: 1024
          minLength: 1
          type: string
        type:
          description: URI for type of error
          minLength: 1
          type: string
      required:
        - status
        - type
        - title
      type: object
    DateOfBirth:
      type: object
      properties:
        day:
          type: string
          pattern: ^\s[0-9]{2}$|^$
          nullable: true
        month:
          type: string
          pattern: ^\s[0-2]{1}\d{1}|3[0-1]{1}|^$
          nullable: true
        year:
          type: string
          pattern: ^\s[0-9]{4}$|^$
          nullable: true

tags:
  - description: Services to fulfill actions for ASquare Commerce Website
    name: ASquare Service
  - description: Authentication Service
    name: Authentication
